ALTER TABLE "ContestStanding"
  ALTER COLUMN "bonusPoints" SET DEFAULT 0,
  ALTER COLUMN "rawScore" DROP DEFAULT;

ALTER TABLE "MonthlyLeaderboard"
  ALTER COLUMN "contests" DROP DEFAULT,
  ALTER COLUMN "wins" DROP DEFAULT,
  ALTER COLUMN "solved" DROP DEFAULT,
  ALTER COLUMN "firstSolves" DROP DEFAULT,
  ALTER COLUMN "updatedAt" DROP DEFAULT;

ALTER TABLE "YearlyLeaderboard"
  ALTER COLUMN "contests" DROP DEFAULT,
  ALTER COLUMN "wins" DROP DEFAULT,
  ALTER COLUMN "solved" DROP DEFAULT,
  ALTER COLUMN "firstSolves" DROP DEFAULT,
  ALTER COLUMN "updatedAt" DROP DEFAULT;
